// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/[slug]" | "/buscar-voo" | "/cadastro/[[...sign-up]]" | "/carros" | "/como-funciona" | "/completar-cadastro" | "/contato" | "/entrar/[[...sign-in]]" | "/eventos" | "/eventos/[slug]" | "/guias" | "/hoteis" | "/onibus" | "/pacotes" | "/passagens" | "/prep" | "/privacidade" | "/roteiro" | "/sobre" | "/termos" | "/voos-baratos"
type AppRouteHandlerRoutes = "/api/airports" | "/api/cep" | "/api/cheap-flights" | "/api/events" | "/api/experiences" | "/api/flights" | "/api/hotels" | "/api/prep" | "/api/prep/checkout" | "/api/roteiro" | "/api/user-profile" | "/api/waitlist"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/airports": {}
  "/api/cep": {}
  "/api/cheap-flights": {}
  "/api/events": {}
  "/api/experiences": {}
  "/api/flights": {}
  "/api/hotels": {}
  "/api/prep": {}
  "/api/prep/checkout": {}
  "/api/roteiro": {}
  "/api/user-profile": {}
  "/api/waitlist": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/buscar-voo": {}
  "/cadastro/[[...sign-up]]": { "sign-up"?: string[]; }
  "/carros": {}
  "/como-funciona": {}
  "/completar-cadastro": {}
  "/contato": {}
  "/entrar/[[...sign-in]]": { "sign-in"?: string[]; }
  "/eventos": {}
  "/eventos/[slug]": { "slug": string; }
  "/guias": {}
  "/hoteis": {}
  "/onibus": {}
  "/pacotes": {}
  "/passagens": {}
  "/prep": {}
  "/privacidade": {}
  "/roteiro": {}
  "/sobre": {}
  "/termos": {}
  "/voos-baratos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
