// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/buscar-voo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buscar-voo">> = Specific
  const handler = {} as typeof import("../../../app/buscar-voo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cadastro/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../../app/cadastro/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/carros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carros">> = Specific
  const handler = {} as typeof import("../../../app/carros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/como-funciona/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/como-funciona">> = Specific
  const handler = {} as typeof import("../../../app/como-funciona/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/completar-cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/completar-cadastro">> = Specific
  const handler = {} as typeof import("../../../app/completar-cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contato">> = Specific
  const handler = {} as typeof import("../../../app/contato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/entrar/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrar/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../../app/entrar/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/eventos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/eventos/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/eventos/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/eventos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/eventos">> = Specific
  const handler = {} as typeof import("../../../app/eventos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guias">> = Specific
  const handler = {} as typeof import("../../../app/guias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hoteis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hoteis">> = Specific
  const handler = {} as typeof import("../../../app/hoteis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onibus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onibus">> = Specific
  const handler = {} as typeof import("../../../app/onibus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pacotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pacotes">> = Specific
  const handler = {} as typeof import("../../../app/pacotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/passagens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/passagens">> = Specific
  const handler = {} as typeof import("../../../app/passagens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/prep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prep">> = Specific
  const handler = {} as typeof import("../../../app/prep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific
  const handler = {} as typeof import("../../../app/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/roteiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roteiro">> = Specific
  const handler = {} as typeof import("../../../app/roteiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre">> = Specific
  const handler = {} as typeof import("../../../app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/termos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/termos">> = Specific
  const handler = {} as typeof import("../../../app/termos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/voos-baratos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voos-baratos">> = Specific
  const handler = {} as typeof import("../../../app/voos-baratos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/airports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airports">> = Specific
  const handler = {} as typeof import("../../../app/api/airports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cep">> = Specific
  const handler = {} as typeof import("../../../app/api/cep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cheap-flights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cheap-flights">> = Specific
  const handler = {} as typeof import("../../../app/api/cheap-flights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../../app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/experiences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiences">> = Specific
  const handler = {} as typeof import("../../../app/api/experiences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/flights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flights">> = Specific
  const handler = {} as typeof import("../../../app/api/flights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hotels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotels">> = Specific
  const handler = {} as typeof import("../../../app/api/hotels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/prep/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prep/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/prep/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/prep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prep">> = Specific
  const handler = {} as typeof import("../../../app/api/prep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roteiro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roteiro">> = Specific
  const handler = {} as typeof import("../../../app/api/roteiro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/waitlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/waitlist">> = Specific
  const handler = {} as typeof import("../../../app/api/waitlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
