// lib/events-data.ts
// Fonte única de dados de eventos — compartilhada entre /eventos e /eventos/[slug]

export interface EventData {
  id:              string
  title:           string
  shortDesc:       string
  longDesc:        string
  date:            string
  location:        string
  venue:           string
  country:         string
  flag:            string
  category:        string
  tag:             string
  tagColor:        string
  imageUrl:        string
  ticketUrl:       string
  ticketLabel:     string
  priceEstimate:   string
  flightFrom:      string
  // Para pré-preencher busca de voos
  destinationIata: string
  // Para pré-preencher busca de hotéis
  hotelCity:       string
  suggestedCheckIn:  string   // YYYY-MM-DD
  suggestedCheckOut: string   // YYYY-MM-DD
  // Dicas práticas
  tips:            string[]
}

export const EVENTS: EventData[] = [
  // ── FUTEBOL BRASILEIRO ──────────────────────────────────
  {
    id:              'athletico-pr',
    title:           'Athletico Paranaense — Brasileirão',
    shortDesc:       'Sinta a atmosfera da Ligga Arena e o calor da torcida rubro-negra.',
    longDesc:        'O Athletico Paranaense é um dos clubes mais vitoriosos do Brasil e tem uma das torcidas mais apaixonadas do país. A Ligga Arena, inaugurada em 1999 e reformada em 2022, é um dos estádios mais modernos do Brasil com capacidade para 42 mil torcedores. Para viajantes estrangeiros, é uma das experiências mais autênticas do futebol brasileiro fora do eixo Rio–São Paulo.',
    date:            'Temporada 2026',
    location:        'Curitiba, Brasil',
    venue:           'Ligga Arena',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'futebol',
    tag:             'Futebol Brasileiro',
    tagColor:        '#16a34a',
    imageUrl:        'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800',
    ticketUrl:       'https://ingressos.athletico.com.br/',
    ticketLabel:     'Comprar ingresso oficial',
    priceEstimate:   'Ingressos a partir de R$ 40',
    flightFrom:      'Voos para Curitiba a partir de R$ 320',
    destinationIata: 'CWB',
    hotelCity:       'Curitiba',
    suggestedCheckIn:  '2026-08-14',
    suggestedCheckOut: '2026-08-16',
    tips: [
      'A Ligga Arena fica no bairro Água Verde — use Uber ou táxi do centro (15 min)',
      'Ingressos esgotam rápido para clássicos — compre com antecedência pelo site oficial',
      'A torcida rubro-negra tem restrição de acesso de torcedores visitantes em alguns setores',
      'Curitiba tem temperatura amena mesmo no verão — leve casaco para a noite',
    ],
  },
  {
    id:              'flamengo',
    title:           'Flamengo — Maracanã',
    shortDesc:       'O maior clube do Brasil no palco mais icônico do futebol mundial.',
    longDesc:        'O Flamengo é o clube com maior torcida do Brasil e um dos maiores da América Latina. Assistir a um jogo do Mengão no Maracanã — o estádio mais famoso do mundo — é uma experiência que vai muito além do futebol. A vibração da torcida rubro-negra, o cântico "Mengão, Mengão" ecoando pelas arquibancadas e o visual deslumbrante do estádio renovado fazem desse evento um dos mais procurados por viajantes internacionais.',
    date:            'Temporada 2026',
    location:        'Rio de Janeiro, Brasil',
    venue:           'Estádio do Maracanã',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'futebol',
    tag:             'Futebol Brasileiro',
    tagColor:        '#16a34a',
    imageUrl:        'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800',
    ticketUrl:       'https://www.futebolcard.com/events?team=flamengo',
    ticketLabel:     'Comprar ingresso — FutebolCard',
    priceEstimate:   'Ingressos a partir de R$ 60',
    flightFrom:      'Voos para o Rio a partir de R$ 280',
    destinationIata: 'GIG',
    hotelCity:       'Rio de Janeiro',
    suggestedCheckIn:  '2026-08-14',
    suggestedCheckOut: '2026-08-17',
    tips: [
      'O Maracanã fica na Zona Norte do Rio — use metrô (linha 2, estação Maracanã)',
      'Ingressos do Flamengo exigem cadastro biométrico no FutebolCard — faça com antecedência',
      'Fique no bairro Ipanema ou Leblon e vá de metrô no dia do jogo',
      'Evite chegar nos últimos 30 min antes do jogo — filas longas nos catracas biométricas',
    ],
  },
  {
    id:              'corinthians',
    title:           'Corinthians — Neo Química Arena',
    shortDesc:       'A Fiel Torcida é uma das mais apaixonadas do mundo.',
    longDesc:        'A Neo Química Arena é o estádio do Corinthians, inaugurado para a Copa do Mundo 2014 e localizado no bairro do Itaquera, na zona leste de São Paulo. Com capacidade para 47 mil pessoas, é um dos estádios mais modernos do Brasil. A Fiel Torcida, como é conhecida a torcida corintiana, é famosa pela intensidade e lealdade — criar um mosaico com 47 mil fãs de vermelho e preto é algo que precisa ser visto ao vivo.',
    date:            'Temporada 2026',
    location:        'São Paulo, Brasil',
    venue:           'Neo Química Arena',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'futebol',
    tag:             'Futebol Brasileiro',
    tagColor:        '#16a34a',
    imageUrl:        'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=800',
    ticketUrl:       'https://www.futebolcard.com/events?team=corinthians',
    ticketLabel:     'Comprar ingresso — FutebolCard',
    priceEstimate:   'Ingressos a partir de R$ 50',
    flightFrom:      'Voos para São Paulo a partir de R$ 220',
    destinationIata: 'GRU',
    hotelCity:       'São Paulo',
    suggestedCheckIn:  '2026-08-14',
    suggestedCheckOut: '2026-08-17',
    tips: [
      'A Neo Química Arena fica em Itaquera — use a Linha 3 do Metrô (estação Corinthians–Itaquera)',
      'Cadastro biométrico no FutebolCard é obrigatório — faça antes de viajar',
      'Fique na região da Paulista ou Vila Olímpia para estar bem localizado na cidade',
      'Para clássicos (Corinthians × Palmeiras), ingressos esgotam dias antes — compre com antecedência',
    ],
  },
  {
    id:              'copa-libertadores',
    title:           'Final da Copa Libertadores',
    shortDesc:       'O maior torneio de clubes das Américas.',
    longDesc:        'A Copa Libertadores é o equivalente sul-americano da Champions League europeia. A final reúne os dois melhores times do continente em uma única partida eliminatória, geralmente realizada em novembro. Buenos Aires, uma das cidades mais vibrantes da América Latina, recebe o evento com toda a intensidade do futebol argentino. Uma experiência imperdível para qualquer apaixonado por futebol.',
    date:            'Nov 2026',
    location:        'Buenos Aires, Argentina',
    venue:           'A definir',
    country:         'Argentina',
    flag:            '🇦🇷',
    category:        'futebol',
    tag:             'Em alta',
    tagColor:        '#F5A623',
    imageUrl:        'https://images.unsplash.com/photo-1551958219-acbc82e6e25b?w=800',
    ticketUrl:       'https://www.conmebol.com/pt/',
    ticketLabel:     'Ingressos — CONMEBOL',
    priceEstimate:   'Preço estimado a partir de R$ 800',
    flightFrom:      'Voos para Buenos Aires a partir de R$ 1.200',
    destinationIata: 'EZE',
    hotelCity:       'Buenos Aires',
    suggestedCheckIn:  '2026-11-26',
    suggestedCheckOut: '2026-11-29',
    tips: [
      'O Aeroporto Internacional de Ezeiza (EZE) fica a 35 km do centro — use o Aerobús ou táxi oficial',
      'Reserve hotel com pelo menos 3 meses de antecedência — a cidade lota para a final',
      'Buenos Aires tem fuso de -3h em relação ao Brasil — verifique o horário do jogo',
      'O bairro de Palermo é ideal para se hospedar — próximo de restaurantes e transporte',
    ],
  },

  // ── AUTOMOBILISMO ────────────────────────────────────────
  {
    id:              'f1-monaco',
    title:           'GP de Fórmula 1 — Mônaco',
    shortDesc:       'A corrida mais glamourosa do mundo.',
    longDesc:        'O Grande Prêmio de Mônaco é a corrida mais icônica do calendário da Fórmula 1. Realizado nas ruas da principado desde 1929, o circuito de Monaco desafia os pilotos com curvas impossíveis, tuneis e grades de proteção a centímetros dos carros. O evento acontece em maio e transforma Monte Carlo em um palco único: iates no porto, pit lane a metros do cassino e o som dos motores ecoando pelas montanhas.',
    date:            'Mai 2026',
    location:        'Monte Carlo, Mônaco',
    venue:           'Circuit de Monaco',
    country:         'Mônaco',
    flag:            '🇲🇨',
    category:        'automobilismo',
    tag:             'Esgotando',
    tagColor:        '#dc2626',
    imageUrl:        'https://images.unsplash.com/photo-1615483585256-a5e24a069ee1?w=800',
    ticketUrl:       'https://www.formula1.com/en/racing/2026/monaco/tickets.html',
    ticketLabel:     'Ingressos oficiais — Formula1.com',
    priceEstimate:   'A partir de R$ 22.000 (€ 3.500)',
    flightFrom:      'Voos para Nice a partir de R$ 6.800',
    destinationIata: 'NCE',
    hotelCity:       'Nice',
    suggestedCheckIn:  '2026-05-22',
    suggestedCheckOut: '2026-05-26',
    tips: [
      'O aeroporto mais próximo é Nice Côte d\'Azur (NCE) — 30 min de carro ou trem até Monaco',
      'Ingressos para as arquibancadas esgotam com 1 ano de antecedência — compre já',
      'Fique em Nice e vá de trem — é muito mais barato que hotéis em Monte Carlo durante o GP',
      'Os melhores pontos gratuitos para ver a corrida ficam na subida do Casino',
    ],
  },
  {
    id:              'f1-brasil',
    title:           'GP de Fórmula 1 — Brasil',
    shortDesc:       'Interlagos é eleito pelos pilotos como um dos melhores circuitos do mundo.',
    longDesc:        'O Grande Prêmio do Brasil realizado no Autódromo de Interlagos é um dos favoritos entre pilotos e torcedores. O circuito técnico, o clima imprevisível de São Paulo e a paixão da torcida brasileira criam uma atmosfera única. Em anos recentes, Interlagos foi palco de corridas memoráveis, com inversões de resultado e emoção até a última volta.',
    date:            'Nov 2026',
    location:        'São Paulo, Brasil',
    venue:           'Autódromo de Interlagos',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'automobilismo',
    tag:             'Automobilismo',
    tagColor:        '#7c3aed',
    imageUrl:        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ticketUrl:       'https://www.formula1.com/en/racing/2026/brazil/tickets.html',
    ticketLabel:     'Ingressos oficiais — Formula1.com',
    priceEstimate:   'A partir de R$ 1.800',
    flightFrom:      'Voos para São Paulo a partir de R$ 320',
    destinationIata: 'GRU',
    hotelCity:       'São Paulo',
    suggestedCheckIn:  '2026-11-13',
    suggestedCheckOut: '2026-11-16',
    tips: [
      'Interlagos fica na zona sul de São Paulo — use metrô + ônibus fretado ou Uber',
      'Os ingressos para as arquibancadas cobertas (Arquibancada K e J) têm a melhor vista',
      'O fim de semana do GP em São Paulo costuma ter chuva — leve capa impermeável',
      'Fique no bairro do Itaim Bibi ou Vila Olímpia — bem localizado e com boa infraestrutura',
    ],
  },
  {
    id:              'arrancada-florida',
    title:           'NHRA Camping World Drag Racing — Gainesville',
    shortDesc:       'O maior evento de arrancada dos Estados Unidos.',
    longDesc:        'O NHRA Gatornationals em Gainesville, Flórida, é uma das provas mais tradicionais do campeonato americano de drag racing. Carros Top Fuel percorrem 400 metros em menos de 4 segundos atingindo velocidades próximas de 500 km/h — a aceleração é tão intensa que o solo treme e a fumaça dos pneus cobre a pista. Uma experiência visceral e única para qualquer fã de automobilismo.',
    date:            'Mar 2026',
    location:        'Gainesville, Flórida, EUA',
    venue:           'Gainesville Raceway',
    country:         'EUA',
    flag:            '🇺🇸',
    category:        'automobilismo',
    tag:             'Automobilismo',
    tagColor:        '#7c3aed',
    imageUrl:        'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
    ticketUrl:       'https://www.nhra.com/tickets',
    ticketLabel:     'Ingressos oficiais — NHRA.com',
    priceEstimate:   'A partir de USD 60 (≈ R$ 360)',
    flightFrom:      'Voos para Orlando a partir de R$ 3.200',
    destinationIata: 'MCO',
    hotelCity:       'Gainesville',
    suggestedCheckIn:  '2026-03-12',
    suggestedCheckOut: '2026-03-15',
    tips: [
      'Voe para Orlando (MCO) e alugue um carro — Gainesville fica a 2h de carro',
      'Leve protetor auricular — os Top Fuels são os veículos mais barulhentos do esporte',
      'Ingressos de final de semana dão acesso aos pits — vale muito a pena',
      'Gainesville tem boa rede de hotéis — reserve na área de Archer Road',
    ],
  },
  {
    id:              'rally-georgia',
    title:           'Rally da Geórgia — WRC',
    shortDesc:       'Velocidade, lama e paisagens deslumbrantes no coração do Cáucaso.',
    longDesc:        'O Rally da Geórgia é uma das etapas mais recentes e já uma das mais espetaculares do Campeonato Mundial de Rally (WRC). As estradas de terra serpenteiam por montanhas e vales do Cáucaso, com trechos noturnos iluminados apenas pelos faróis dos carros e pelos archotes da torcida. Tbilisi, a capital, oferece uma mistura única de arquitetura medieval, gastronomia caucasiana e hospitalidade calorosa.',
    date:            'Out 2026',
    location:        'Tbilisi, Geórgia',
    venue:           'Shota Rustaveli Ave (Parque de Serviço)',
    country:         'Geórgia',
    flag:            '🇬🇪',
    category:        'automobilismo',
    tag:             'Automobilismo',
    tagColor:        '#7c3aed',
    imageUrl:        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ticketUrl:       'https://www.wrc.com/en/wrc/calendar/',
    ticketLabel:     'Informações — WRC.com',
    priceEstimate:   'Acesso gratuito em muitos trechos especiais',
    flightFrom:      'Voos para Tbilisi a partir de R$ 5.800',
    destinationIata: 'TBS',
    hotelCity:       'Tbilisi',
    suggestedCheckIn:  '2026-10-15',
    suggestedCheckOut: '2026-10-19',
    tips: [
      'O aeroporto de Tbilisi (TBS) fica a 20 min do centro — use táxi ou metrô',
      'Muitos trechos do Rally são de acesso gratuito — veja o roadbook oficial do WRC',
      'A Geórgia não requer visto para brasileiros — passaporte válido é suficiente',
      'Tbilisi tem excelente gastronomia — experimente khinkali (dumplings georgianos) e vinho natural',
    ],
  },

  // ── SHOWS ────────────────────────────────────────────────
  {
    id:              'lollapalooza-brasil',
    title:           'Lollapalooza Brasil 2026',
    shortDesc:       'O maior festival de música pop e rock do Brasil.',
    longDesc:        'O Lollapalooza Brasil é um dos maiores festivais de música do mundo e reúne anualmente centenas de milhares de pessoas no Autódromo de Interlagos em São Paulo. Com palcos simultâneos, atrações internacionais de primeira linha e uma experiência de festival completa com gastronomia e arte, é um evento que vai muito além da música.',
    date:            'Mar 2026',
    location:        'São Paulo, Brasil',
    venue:           'Autódromo de Interlagos',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'shows',
    tag:             'Em alta',
    tagColor:        '#F5A623',
    imageUrl:        'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    ticketUrl:       'https://www.lollapaloozabr.com/',
    ticketLabel:     'Ingressos — lollapaloozabr.com',
    priceEstimate:   'A partir de R$ 495 (1 dia)',
    flightFrom:      'Voos para São Paulo a partir de R$ 320',
    destinationIata: 'GRU',
    hotelCity:       'São Paulo',
    suggestedCheckIn:  '2026-03-26',
    suggestedCheckOut: '2026-03-30',
    tips: [
      'Interlagos fica na zona sul de SP — use metrô até Santo Amaro e depois ônibus fretado',
      'Leve protetor solar, pois o festival é ao ar livre e começa durante o dia',
      'Mochila pequena e transparente é recomendada para facilitar a entrada',
      'Fique em hotéis próximos ao metrô — linha 5 (Lilás) é a mais conveniente',
    ],
  },
  {
    id:              'rock-in-rio',
    title:           'Rock in Rio 2026',
    shortDesc:       'O maior festival de música do mundo, em casa.',
    longDesc:        'Rock in Rio é o maior festival de música do mundo em número de público e um dos mais antigos. Realizado na Cidade do Rock no bairro de Jacarepaguá no Rio de Janeiro, reúne artistas nacionais e internacionais de múltiplos gêneros ao longo de vários dias. Com capacidade para 100 mil pessoas por dia, é um evento que transforma o Rio e representa o melhor da hospitalidade e cultura brasileira.',
    date:            'Set 2026',
    location:        'Rio de Janeiro, Brasil',
    venue:           'Cidade do Rock — Parque Olímpico',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'shows',
    tag:             'Shows',
    tagColor:        '#db2777',
    imageUrl:        'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
    ticketUrl:       'https://www.rockinrio.com/rio/ingresso/',
    ticketLabel:     'Ingressos — rockinrio.com',
    priceEstimate:   'A partir de R$ 650 (1 dia)',
    flightFrom:      'Voos para o Rio a partir de R$ 280',
    destinationIata: 'GIG',
    hotelCity:       'Rio de Janeiro',
    suggestedCheckIn:  '2026-09-18',
    suggestedCheckOut: '2026-09-22',
    tips: [
      'A Cidade do Rock fica em Jacarepaguá — use o BRT Transolímpica ou shuttle oficial',
      'Ingressos esgotam em poucas horas após o lançamento — siga as redes sociais do evento',
      'Barra da Tijuca e Recreio são os bairros mais próximos da Cidade do Rock',
      'O festival tem opções para todos os gêneros musicais — veja a programação antes de escolher o dia',
    ],
  },

  // ── CULTURA ──────────────────────────────────────────────
  {
    id:              'carnaval-rio',
    title:           'Carnaval do Rio de Janeiro 2026',
    shortDesc:       'O maior espetáculo da Terra.',
    longDesc:        'O Carnaval do Rio de Janeiro é considerado o maior e mais famoso carnaval do mundo, com mais de 2 milhões de pessoas por dia nas ruas durante os 4 dias de festa. O Sambódromo do Marquês de Sapucaí sedia os desfiles das escolas de samba do Grupo Especial — um espetáculo de mais de 3 horas por escola, com fantasias, alegorias, samba-enredo e emoção. Cada detalhe é trabalhado por meses por milhares de pessoas.',
    date:            'Fev 2026',
    location:        'Rio de Janeiro, Brasil',
    venue:           'Sambódromo Marquês de Sapucaí',
    country:         'Brasil',
    flag:            '🇧🇷',
    category:        'cultura',
    tag:             'Cultura',
    tagColor:        '#0891b2',
    imageUrl:        'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=800',
    ticketUrl:       'https://www.liesa.com.br/',
    ticketLabel:     'Ingressos — LIESA (oficial)',
    priceEstimate:   'Arquibancada a partir de R$ 80 · Camarote a partir de R$ 1.500',
    flightFrom:      'Voos para o Rio a partir de R$ 280',
    destinationIata: 'GIG',
    hotelCity:       'Rio de Janeiro',
    suggestedCheckIn:  '2026-02-13',
    suggestedCheckOut: '2026-02-18',
    tips: [
      'Reserve hotel com 6 a 12 meses de antecedência — o Rio lota completamente durante o Carnaval',
      'Os desfiles do Grupo Especial são na sexta e sábado de Carnaval — os melhores dias',
      'Arquibancada do setor 9 tem ótima visibilidade e melhor custo-benefício',
      'Compre ingressos apenas pelo site oficial da LIESA — evite cambistas',
    ],
  },
  {
    id:              'hanami-japao',
    title:           'Hanami — Festival das Cerejeiras no Japão',
    shortDesc:       'Uma das tradições mais belas e únicas do mundo.',
    longDesc:        'O Hanami é a tradição japonesa de contemplar as flores de cerejeira (sakura) durante o breve período em que estão em plena floração — geralmente de 1 a 2 semanas entre março e abril. Parques, jardins e marginais de rios se enchem de famílias, amigos e viajantes que montam piqueniques sob as árvores cor-de-rosa. Tóquio, Kyoto e Osaka são os destinos mais procurados. É uma experiência que combina beleza, cultura e uma profunda filosofia japonesa sobre a efemeridade da vida.',
    date:            'Mar–Abr 2026',
    location:        'Tóquio / Kyoto / Osaka, Japão',
    venue:           'Parques públicos (Ueno, Maruyama, Shinjuku Gyoen)',
    country:         'Japão',
    flag:            '🇯🇵',
    category:        'cultura',
    tag:             'Cultura',
    tagColor:        '#0891b2',
    imageUrl:        'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    ticketUrl:       'https://www.japan.travel/en/spot/1598/',
    ticketLabel:     'Guia oficial — japan.travel',
    priceEstimate:   'Acesso gratuito aos parques públicos',
    flightFrom:      'Voos para Tóquio a partir de R$ 5.200',
    destinationIata: 'NRT',
    hotelCity:       'Tokyo',
    suggestedCheckIn:  '2026-03-25',
    suggestedCheckOut: '2026-04-05',
    tips: [
      'A floração varia ano a ano — consulte o Japan Meteorological Corporation para previsão exata',
      'Reserve hotel com 4 a 6 meses de antecedência — é o período mais concorrido do turismo no Japão',
      'O Japan Rail Pass compensa se você for visitar Tóquio + Kyoto + Osaka',
      'Os melhores parques em Tóquio: Ueno, Shinjuku Gyoen e Yoyogi',
    ],
  },
]

export function getEventBySlug(slug: string): EventData | undefined {
  return EVENTS.find(e => e.id === slug)
}

export function getRelatedEvents(current: EventData, limit = 3): EventData[] {
  return EVENTS
    .filter(e => e.id !== current.id && e.category === current.category)
    .slice(0, limit)
}
